resolve '/etc/nixos' symlink
fix
```
error: path '/etc/nixos' is not a flake (because it's not a directory)
```

because my '/etc/nixos' is a symlink to '$HOME/dotfiles'